# Generated by Django 5.1.7 on 2025-03-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='intensity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(choices=[('strength', 'Strength Training'), ('cardio', 'Cardio'), ('hiit', 'HIIT'), ('yoga', 'Yoga/Flexibility'), ('calisthenics', 'Calisthenics')], max_length=20),
        ),
    ]
