# Generated by Django 5.1.7 on 2025-03-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_intensity_alter_workout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(choices=[('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('weight_training', 'Weight Training'), ('yoga', 'Yoga/Flexibility'), ('hiit', 'HIIT'), ('cardio', 'Cardio'), ('other', 'Other')], max_length=20),
        ),
    ]
